version: '2.27'
services:
  hostCollector:
    build: ./hostCollector
    container_name: hostCollector
    ports:
      - "18081:18081"
    networks:
      - demo_net

  hostMonitor:
    build: ./hostMonitor
    container_name: hostMonitor
    ports:
      - "18080:18080"
    networks:
      - demo_net
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: 'abc123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 123'
    ports:
      - "3306:3306"
    volumes:
      - /app/mysql/db:/var/lib/mysql
      - /app/mysql/conf/my.cnf:/etc/my.cnf
      - /app/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - demo_net
    command: --default-authentication-plugin=mysql_native_password

networks:
  demo_net:
